#!/bin/sh
# Start/stop the ip daemon.
#
### BEGIN INIT INFO
# Provides:          ip
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
# Default-Start:     S 2 3 4 5
# Default-Stop:
# Short-Description: IP email
# Description:       Send IP to email
### END INIT INFO

SENDGRID_APIKEY=""
TO_EMAIL=""

case "$1" in
  start)
    _IP=$(hostname -I) || true
    if [ "$_IP" ]; then
      python /home/pi/pi-email-ip/send.py "$_IP" "$SENDGRID_APIKEY" "$TO_EMAIL"
    fi
    ;;
  stop)

    ;;
  *)
    echo "Usage: /etc/init.d/ip {start|stop}"
    exit 1
    ;;
esac

 exit 0
